"""empty message

Revision ID: 88ebfaf8824b
Revises: c935a6121f81
Create Date: 2023-09-08 17:35:14.892247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ebfaf8824b'
down_revision = 'c935a6121f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=55), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
